"""Adicionando nova tabela1

Revision ID: 6b14acdad3a6
Revises: 9f7cc3abb0ee
Create Date: 2025-02-14 15:50:18.911103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b14acdad3a6'
down_revision: Union[str, None] = '9f7cc3abb0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employees', 'users', ['user_creator_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_constraint('users_employee_id_fkey', 'users', type_='foreignkey')
    op.drop_constraint('users_user_creator_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['user_creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_user_creator_id_fkey', 'users', 'users', ['user_creator_id'], ['id'])
    op.create_foreign_key('users_employee_id_fkey', 'users', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    # ### end Alembic commands ###
